package cool.blink.front.css.template;

public final class Base64Backgrounds {

    public static final String absurdity = "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAH0lEQVQIW2NgYODjBWJWKOZgQOKwQDAKByLAgSTACQAp6QE8mK8aTgAAAABJRU5ErkJggg==";
    public static final String brilliant = "iVBORw0KGgoAAAANSUhEUgAAAAMAAAADCAQAAAD8IX00AAAAE0lEQVR4AWNgYNgsvRlCgCgwBAA6YQXPi9F1OAAAAABJRU5ErkJggg==";
    public static final String darkCircles = "iVBORw0KGgoAAAANSUhEUgAAAAoAAAAMCAQAAADxYuQrAAAAWklEQVQI12NgAAFZBgRQBBGSDJITRRFiPUA+w0RRIIUCkPlGQGiGKq3XI9mo1iHLoIcsqAaltRjQ7URzB9hONHcAAcgVCHtBtqICI4Z6LaA8sp1GMCOQ7QSyAcvLDf4Fs8YtAAAAAElFTkSuQmCC";
    public static final String darkDot = "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHUlEQVQIW2NgY2OzYUACYL6+vn4UsgAynwwBEB8ARuIGpsZxGOoAAAAASUVORK5CYII=";
    public static final String outlets = "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAICAQAAAB0OpaOAAAAHElEQVR4AWNgYDAONQZiBhABhEAGXCQUxiCsBgC8qgzSEgW+UwAAAABJRU5ErkJggg==";
    public static final String whiteCarbonFiber = "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAQAAAAD+Fb1AAAAIElEQVR4AWOYUjKlZGrn1E4wY/q66esYQDwQhwHEAzEAPjcRzX34FvsAAAAASUVORK5CYII=";

}
